# Generated by Django 4.0.2 on 2023-03-12 00:33

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('posicao', models.CharField(choices=[('GO', 'Goleiro'), ('LD', 'Lateral Direito'), ('LE', 'Lateral Esquerdo'), ('ZC', 'Zagueiro'), ('VOL', 'Volante'), ('MLG', 'Meia de Ligação'), ('MLD', 'Meia de Ligação Direita'), ('MLE', 'Meia de Ligação Esquerda'), ('MAT', 'Meia Atacante'), ('PTE', 'Ponta Esquerda'), ('PTD', 'Ponta Direita'), ('CA', 'Centroavante')], max_length=10)),
                ('possuiProblemaSaude', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=2)),
                ('altura', models.IntegerField()),
                ('massa', models.IntegerField()),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=35)),
                ('dataNascimento', models.DateField()),
                ('qualProblema', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('comoSoube', models.CharField(choices=[('I', 'Internet'), ('J', 'Jornal'), ('R', 'Rádio'), ('O', 'Outros')], max_length=15)),
                ('formaPagamento', models.CharField(max_length=10)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('nome', models.CharField(max_length=50)),
                ('observacoes', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('dataNascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('numero', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMovimento', models.CharField(choices=[('P', 'Pix'), ('D', 'Dinheiro'), ('O', 'Outro')], max_length=1)),
                ('dataMovimento', models.DateField()),
                ('valorPago', models.DecimalField(choices=[(50.0, 'R$50,00'), (100.0, 'R$100,00'), (150.0, 'R$150,00'), (200.0, 'R$200,00'), (250.0, 'R$250,00'), (300.0, 'R$300,00')], decimal_places=2, max_digits=7)),
                ('situacao', models.CharField(choices=[('0', 'OK'), ('1', 'Inadimplente')], max_length=1)),
                ('ficha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ficha')),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='responsavel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.responsavel'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='valores_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.valores'),
        ),
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('descricao', models.CharField(max_length=255)),
                ('ficha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ficha')),
            ],
        ),
    ]
