# Generated by Django 4.0.2 on 2023-03-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='situacao',
            field=models.CharField(choices=[('0', 'OK'), ('1', 'Inadimplente')], max_length=1),
        ),
    ]
