# Generated by Django 4.0.2 on 2023-03-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_financeiro_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='dataMovimento',
            field=models.DateField(),
        ),
    ]
